### ISSUE TITLE
希望能增加对open graph的支持

### ISSUE THREAD

**Issue by gaoyuear** [ShinChven/ShareMoments#1]
软件非常有用，谢谢
希望在获取图片，标题和描述的时候能够支持open graph标准。（好像现在图片是支持的，表述还不行）
https://blog.kissmetrics.com/open-graph-meta-tags/

**Comment by ShinChven** [comment]
感谢提供建议，原先是使用的open graph，后来遇到有些网站不兼容，就改成手工读全文了。
下次版本升级会再加上去。

**Comment by ShinChven** [comment]
已更新
