### ISSUE TITLE
有图片抓不到

### ISSUE THREAD

**Issue by yueduz** [ShinChven/ShareMoments#21]
https://blog.ayahuo.com/content/EARIN%20M-2

**Comment by ShinChven** [comment]
请兼容OpenGraph ，并以text/html输出，app不会去抓你js加载的内容。 
目前只支持完整路径，不支持相对路径。

**Comment by yueduz** [comment]
相对路径应该只是个正则表达式的问题吧，打死不支持？源码给看一下呗

**Comment by ShinChven** [comment]
https://github.com/ShinChven/ShareMoments/issues/19
