### ISSUE TITLE
一键分享多个链接到微信朋友圈

### ISSUE THREAD

**Issue by hscmcc1** [ShinChven/ShareMoments#26]
大神你好，我这边有个需求，需要一键分享多个链接到朋友圈，最好是一个命令实现，里面可以传入网址，请问能实现吗？

**Comment by ShinChven** [comment]
不行的，微信SDK只支持一次分享一个链接到朋友圈。

**Comment by ShinChven** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317340&token=&lang=zh_CN

**Comment by hscmcc1** [comment]
嗯好的，非常感谢！
