### ISSUE TITLE
相对链接的图片地址没提取对

### ISSUE THREAD

**Issue by yueduz** [ShinChven/ShareMoments#27]
![screenshot_20190201-230926](https://user-images.githubusercontent.com/1448159/52132760-d4d36480-267a-11e9-8da4-bd0a17fc488e.png)
https://blog.ayahuo.com/content/ArchLinux申请https证书

**Comment by ShinChven** [comment]
检查过了，你的相对路径太纠结，不打算支持。
相对路径只支持缺少host的链接。

你可以使用1.6.11版新增的媒体文件列表工具debug，建议补全缺失的路径 /content/assets/

> <img src=\"assets/1549029984983_9ca23d67b23879b59fa6de2663e0dd64.jpg\"
