### ISSUE TITLE
一人血书请求支持分享到QQ

### ISSUE THREAD

**Issue by Ahua9527** [ShinChven/ShareMoments#29]
一人血书请求支持分享到QQ

**Comment by ShinChven** [comment]
暂无支援QQ的计划。

**Comment by Ahua9527** [comment]
Tim也行啊😀

SHINCHVEN <notifications@github.com> 于 2019年6月17日周一 22:54写道：

**Comment by ShinChven** [comment]
😣不想花时间折腾QQ的产品。开发平台注册超烦。
