### ISSUE TITLE
如果第一张图是gif，他没有抓取第一张图而是找下一张非gif

### ISSUE THREAD

**Issue by yueduz** [ShinChven/ShareMoments#9]

**Comment by ShinChven** [comment]
是先从header里面找起，再去找body里面的。

**Comment by yueduz** [comment]
https://blog.ayahuo.com/content/桌面刷新的正确操作姿势

他找不到我的图片了，以前都可以的

SHINCHVEN <notifications@github.com> 于 2018年6月14日周四 08:00写道：

**Comment by ShinChven** [comment]
我看过你的博客了，你的博客使用的是JavaScript后加载，无法获取。请参考[这里](https://github.com/ShinChven/ShareMoments/blob/master/%E4%BD%BF%E7%94%A8OpenGraph%E6%A0%87%E8%AE%B0%E4%BD%A0%E7%9A%84%E7%BD%91%E9%A1%B5%E5%86%85%E5%AE%B9.md)进行兼容。

**Comment by yueduz** [comment]
我给魔法分享返回的是纯html

SHINCHVEN <notifications@github.com> 于 2018年6月15日周五 15:39写道：

**Comment by yueduz** [comment]
lei阅读中 <yueduz@gmail.com> 于 2018年6月15日周五 15:41写道：

**Comment by ShinChven** [comment]
1. 在解析dom的时候只查找了jpg、png、webp。
2. 请在html里面返回opengraph，以便获取内容。

**Comment by yueduz** [comment]
我发现问题了，如果图片地址是相对链接就找不到图片。我换成绝对地址就行了。

SHINCHVEN <notifications@github.com> 于 2018年6月18日周一 14:57写道：

**Comment by ShinChven** [comment]
@yueduz 1.6.2 中已经摆平gif。 Google play store beta 已提交审核。
